const KEY="kartikTask3Todos";let tasks=load(),filter="all";
const form=document.querySelector("#todoForm"),input=document.querySelector("#taskInput"),list=document.querySelector("#todoList"),empty=document.querySelector("#emptyState"),msg=document.querySelector("#formMessage");
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks))}
function visible(){return filter==="active"?tasks.filter(x=>!x.done):filter==="completed"?tasks.filter(x=>x.done):tasks}
function render(){list.innerHTML="";visible().forEach(t=>{const li=document.createElement("li");li.className="todo"+(t.done?" done":"");li.dataset.id=t.id;li.innerHTML=`<button class="check" data-action="toggle" aria-label="${t.done?"Mark active":"Mark completed"}">${t.done?"✓":""}</button><span class="text"></span><div class="actions"><button data-action="edit">Edit</button><button class="del" data-action="delete">Delete</button></div>`;li.querySelector(".text").textContent=t.text;list.appendChild(li)});empty.hidden=visible().length>0;document.querySelector("#totalCount").textContent=tasks.length;document.querySelector("#activeCount").textContent=tasks.filter(x=>!x.done).length;document.querySelector("#completedCount").textContent=tasks.filter(x=>x.done).length}
form.addEventListener("submit",e=>{e.preventDefault();const text=input.value.trim();if(!text){msg.textContent="Please enter a task.";return}tasks.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2),text,done:false});save();render();form.reset();msg.textContent="Task added successfully.";input.focus()});
document.querySelector(".filters").addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()});
list.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const li=b.closest(".todo"),t=tasks.find(x=>x.id===li.dataset.id);if(!t)return;if(b.dataset.action==="toggle")t.done=!t.done;if(b.dataset.action==="delete")tasks=tasks.filter(x=>x.id!==t.id);if(b.dataset.action==="edit"){const v=prompt("Edit task:",t.text);if(v&&v.trim())t.text=v.trim()}save();render()});
document.querySelector("#clearCompleted").addEventListener("click",()=>{tasks=tasks.filter(x=>!x.done);save();render();msg.textContent="Completed tasks cleared."});render();